apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "leads-scraper-service.fullname" . }}
  labels:
    {{- include "leads-scraper-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "leads-scraper-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "leads-scraper-service.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "leads-scraper-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if eq .Values.config.grpc.environment "development" }}
      initContainers:
        - name: wait-for-redis
          image: busybox:1.28
          command:
            - sh
            - -c
            - until nc -z -w1 {{ .Values.config.redis.host }} {{ .Values.config.redis.port }}; do echo waiting for Redis; sleep 2; done;
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            # Enable gRPC mode
            {{- if .Values.config.grpc.enabled }}
            - "--grpc"
            # gRPC configuration
            - "--grpc-port={{ .Values.config.grpc.port }}"
            - "--grpc-deadline={{ .Values.config.grpc.deadline }}"
            - "--grpc-retries={{ .Values.config.grpc.retries }}"
            - "--grpc-retry-delay={{ .Values.config.grpc.retryDelay }}"
            - "--service-name={{ .Values.config.grpc.serviceName }}"
            - "--environment={{ .Values.config.grpc.environment }}"
            {{- end }}
            # Database configuration
            - "--db-url={{ include "leads-scraper-service.postgresql.dsn" . }}"
            - "--db-max-idle-connections={{ .Values.config.database.maxIdleConnections }}"
            - "--db-max-open-connections={{ .Values.config.database.maxOpenConnections }}"
            - "--db-max-connection-lifetime={{ .Values.config.database.maxConnectionLifetime }}"
            - "--db-max-connection-retry-timeout={{ .Values.config.database.maxConnectionRetryTimeout }}"
            - "--db-retry-sleep={{ .Values.config.database.retrySleep }}"
            - "--db-query-timeout={{ .Values.config.database.queryTimeout }}"
            - "--db-max-connection-retries={{ .Values.config.database.maxConnectionRetries }}"
            # Redis configuration
            {{- if .Values.config.redis.enabled }}
            - "--redis-enabled=true"
            - "--redis-url={{ .Values.config.redis.dsn }}"
            - "--redis-workers={{ .Values.config.redis.workers }}"
            - "--redis-retry-interval={{ .Values.config.redis.retryInterval }}"
            - "--redis-max-retries={{ .Values.config.redis.maxRetries }}"
            - "--redis-retention-days={{ .Values.config.redis.retentionDays }}"
            {{- end }}
            # Monitoring and logging
            {{- if .Values.config.newrelic.enabled }}
            - "--newrelic-key={{ .Values.config.newrelic.key }}"
            {{- end }}
            - "--log-level={{ .Values.config.logging.level }}"
            # Core scraper settings
            - "-c={{ .Values.config.scraper.concurrency }}"
            - "-depth={{ .Values.config.scraper.depth }}"
            - "-lang={{ .Values.config.scraper.language }}"
            - "-radius={{ .Values.config.scraper.searchRadius }}"
            - "-zoom={{ .Values.config.scraper.zoomLevel }}"
            - "-redis-enabled={{ .Values.config.redis.enabled }}"
            - "-redis-url={{ .Values.config.redis.dsn }}"
            - "-redis-workers={{ .Values.config.redis.workers }}"
            # Optional features
            {{- if .Values.config.scraper.emailExtraction }}
            - "-email"
            {{- end }}
            {{- if .Values.config.scraper.fastMode }}
            - "-fast-mode"
            {{- end }}
            {{- if .Values.config.scraper.exitOnInactivity }}
            - "-exit-on-inactivity={{ .Values.config.scraper.exitOnInactivity }}"
            {{- end }}
            {{- if .Values.config.scraper.proxies }}
            - "-proxies={{ .Values.config.scraper.proxies }}"
            {{- end }}
            # AWS Configuration (if provided)
            {{- if .Values.config.aws.accessKey }}
            - "-aws-access-key={{ .Values.config.aws.accessKey }}"
            {{- end }}
            {{- if .Values.config.aws.secretKey }}
            - "-aws-secret-key={{ .Values.config.aws.secretKey }}"
            {{- end }}
            {{- if .Values.config.aws.region }}
            - "-aws-region={{ .Values.config.aws.region }}"
            {{- end }}
            {{- if .Values.config.aws.lambda.enabled }}
            - "-aws-lambda"
            {{- end }}
            {{- if .Values.config.aws.lambda.invoker }}
            - "-aws-lambda-invoker"
            {{- end }}
            - "-aws-lambda-chunk-size={{ .Values.config.aws.lambda.chunkSize }}"
            {{- if .Values.config.aws.lambda.functionName }}
            - "-function-name={{ .Values.config.aws.lambda.functionName }}"
            {{- end }}
            {{- if .Values.config.aws.s3.bucket }}
            - "-s3-bucket={{ .Values.config.aws.s3.bucket }}"
            {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
            {{- if .Values.config.grpc.enabled }}
            - name: grpc
              containerPort: {{ .Values.config.grpc.port }}
              protocol: TCP
            {{- end }}
          {{- if .Values.web.livenessProbe }}
          livenessProbe:
            {{- if .Values.web.livenessProbe.http }}
            httpGet:
              path: {{ .Values.web.livenessProbe.http.path }}
              port: {{ .Values.web.livenessProbe.http.port }}
            initialDelaySeconds: {{ .Values.web.livenessProbe.http.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.livenessProbe.http.periodSeconds }}
            {{- end }}
            {{- if and .Values.config.grpc.enabled .Values.web.livenessProbe.grpc }}
            tcpSocket:
              port: {{ .Values.web.livenessProbe.grpc.tcpSocket.port }}
            initialDelaySeconds: {{ .Values.web.livenessProbe.grpc.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.livenessProbe.grpc.periodSeconds }}
            {{- end }}
          {{- end }}
          {{- if .Values.web.readinessProbe }}
          readinessProbe:
            {{- if .Values.web.readinessProbe.http }}
            httpGet:
              path: {{ .Values.web.readinessProbe.http.path }}
              port: {{ .Values.web.readinessProbe.http.port }}
            initialDelaySeconds: {{ .Values.web.readinessProbe.http.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.readinessProbe.http.periodSeconds }}
            {{- end }}
            {{- if and .Values.config.grpc.enabled .Values.web.readinessProbe.grpc }}
            tcpSocket:
              port: {{ .Values.web.readinessProbe.grpc.tcpSocket.port }}
            initialDelaySeconds: {{ .Values.web.readinessProbe.grpc.initialDelaySeconds }}
            periodSeconds: {{ .Values.web.readinessProbe.grpc.periodSeconds }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
