package constants

const (
	EMPTY = ""

	// Fixed values
	API_KEY_REQUESTS_PER_SECOND         = 10000
	API_KEY_REQUESTS_PER_DAY            = 360000000
	API_KEY_CONCURRENT_REQUESTS         = 100000
	API_KEY_ENFORCE_HTTPS               = true
	API_KEY_ROTATION_FREQUENCY_DAYS     = 10 // 10 days
	API_KEY_DEFAULT_DATA_CLASSIFICATION = "public"
)
